[tool.ruff]
target-version = "py38"
src = ["."]
line-length = 88

[tool.ruff.lint]
# Enable pycodestyle (E), pyflakes (F), and bugbear (B) rules
select = ["E", "F", "B"]

# Ignore line length violations; ruff format does its best and we can rely on
# that
ignore = ["E501"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
